ENVIRONMENT : dev
DATABASE_CONNECTION :
    DRIVER: '{ODBC Driver 17 for SQL Server}'
    SERVER: 'localhost'
    DATABASE: 'OneEnergyDB'
    TRUSTED_CONNECTION: 'yes'
LOG_FILE_PATH : "../share_logs"
DEBUG_MODE : "NO"
API_KEYS :
TRANSIENT_DATA_PATH : "../transient_data"